Repository BookkeepingProjectGroup/CMSC_495_Bookkeeping_Project, pull requests merged in 2018-12, with the labels that each got.

#41 JavaScript - New enum, utility function, fixes
  Files/js/app.js
Labels: ready to merge

#42 CSS - Media & Style updates
  Files/css/media.css
  Files/css/styles.css
Labels: ready to merge

#44 JavaScript/CSS - Account creation module + updates
  Files/css/styles.css
  Files/js/app.js
Labels: ready to merge

#45 JavaScript - Create Account handler
  Files/js/app.js
Labels: ready to merge

#46 PHP - add_document.php
  Files/php/add_document.php
Labels: ready to merge

#48 CSS - Print and table changes
  Files/css/media.css
  Files/css/styles.css
Labels: ready to merge

#49 JavaScript/CSS - Add Document modal expansion
  Files/css/styles.css
  Files/js/app.js
Labels: ready to merge

#47 PHP/SQL/JSON - Endpoint create_user.php
  Files/json/usersLogon.json
  Files/php/DatabaseException.php
  Files/php/DuplicateException.php
  Files/php/UsersConnection.php
  Files/php/create_user.php
  Files/php/logout.php
  Files/sql/CreateDatabases.sql
Labels: ready to merge

#50 CSS - Fixed table header on scroll
  Files/css/media.css
  Files/css/styles.css
Labels: ready to merge

#51 CSS - Print portrait breakpoints
  Files/css/media.css
Labels: ready to merge

#52 JavaScript/JSON - Patches, updates, etc.
  Files/js/app.js
  Files/json/get_accounts.json
  Files/json/get_customers.json
  Files/json/get_documents.json
  Files/json/get_general_ledger_rows.json
  Files/json/get_vendors.json
Labels: ready to merge

#53 PHP/JSON - Addition of end-point create_default_accounts.php
  Files/json/defaultAccounts.json
  Files/php/PhpConnection.php
  Files/php/create_default_accounts.php
Labels: ready to merge

#56 JavaScript/CSS - Account addition modals/handlers
  Files/css/styles.css
  Files/js/app.js
Labels: ready to merge

#55 PHP - add end-point add_account.php
  Files/php/PhpConnection.php
  Files/php/add_account.php
Labels: question, ready to merge

#57 JavaScript/JSON/CSS - Updates
  Files/css/styles.css
  Files/js/app.js
  Files/json/get_documents.json
Labels: ready to merge

#59 PHP - End-point get_documents.php
  Files/php/PhpConnection.php
  Files/php/get_documents.php
Labels: ready to merge

#58 JavaScript/CSS - Masthead module, doc addition updates, etc
  Files/css/styles.css
  Files/js/app.js
Labels: ready to merge

#60 PHP - get_accounts.php
  Files/php/PhpConnection.php
  Files/php/get_accounts.php
Labels: ready to merge

#63 PHP - End-point get_general_ledger_rows.php
  Files/php/get_general_ledger_rows.php
Labels: ready to merge

#61 JavaScript/HTML - Documentation, fixes/updates, minified file, etc
  Files/index.html
  Files/js/app.js
  Files/js/app.min.js
Labels: ready to merge

#62 CSS - Cleanup and formatting
  Files/css/media.css
  Files/css/styles.css
Labels: ready to merge

#64 CSS - Format Fixes
  Files/css/media.css
  Files/css/styles.css
Labels: ready to merge

#65 JavaScript/JSON - Updates
  Files/.htaccess
  Files/js/app.js
  Files/js/app.min.js
  Files/json/get_accounts.json
  Files/json/get_documents.json
  Files/json/get_general_ledger_rows.json
Labels: ready to merge

#66 Documentation - Updates
  Documentation/Bookkeeping Project Plan.docx
  Documentation/Documents/Group4_DesignPlan.pdf
  Documentation/Documents/Group4_Phase1Report.pdf
  Documentation/Documents/Group4_Phase2Report.pdf
  Documentation/Documents/Group4_Phase3Report.pdf
  Documentation/Documents/Group4_ProjectPlan.pdf
  Documentation/Documents/Group4_UserGuide.pdf
  Documentation/PullRequestTutorial.md
  README.md
Labels: ready to merge

#67 JavaScript - Bug fixes, updates
  Files/js/app.js
  Files/js/app.min.js
Labels: review requested

#68 htaccess - Create .htaccess for json directory.
  Files/json/.htaccess
  Files/sql/.htaccess
Labels: ready to merge

#69 PHP - File reorganization, ini.php
  Files/php/add_account.php
  Files/php/add_customer.php
  Files/php/add_document.php
  Files/php/add_vendor.php
  Files/php/create_default_accounts.php
  Files/php/create_user.php
  Files/php/get_accounts.php
  Files/php/get_customers.php
  Files/php/get_documents.php
  Files/php/get_general_ledger_rows.php
  Files/php/get_vendors.php
  Files/php/include/.htaccess
  Files/php/include/AuthenticationConnection.php
  Files/php/include/DatabaseConnection.php
  Files/php/include/DatabaseException.php
  Files/php/include/DuplicateException.php
  Files/php/include/PasswordsConnection.php
  Files/php/include/PhpConnection.php
  Files/php/include/UsersConnection.php
  Files/php/include/ini.php
  Files/php/login.php
  Files/php/logout.php
  Files/php/set_password.php
Labels: ready to merge

#70 PHP - Add secure session settings to ini.php.
  Files/php/include/ini.php
Labels: ready to merge

#71 PHP - Comment-out `session.cookie_secure` line in ini.php.
  Files/php/include/ini.php
Labels: ready to merge

#73 JavaScript/CSS - Portrait view adjustments
  Files/css/media.css
  Files/css/styles.css
  Files/js/app.js
  Files/js/app.min.js
Labels: ready to merge
